title: Ong Jia Yue  # your name (or website title) here
logo: "/images/20230701_110920.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A single with no kids
  <br><br>
  I get lost in data most of the time. 
  <br><br>
  <a href="https://www.linkedin.com/in/jia-yue-ong?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B3V6GRvBmRbelbTfXAe%2Fybg%3D%3D">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
